services:
  server:
    container_name: nestjs-boilerplate
    image: nestjs-boilerplate:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${APP_WEBSOCKET_PORT}:${APP_WEBSOCKET_PORT}'
    networks:
      - nestjs-boilerplate-network

  worker:
    container_name: nestjs-boilerplate-worker
    image: nestjs-boilerplate-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_WORKER=true
    ports:
      - '${APP_WORKER_PORT}:${APP_WORKER_PORT}'
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis:7.0.1-alpine
    container_name: nestjs-boilerplate-redis
    restart: always
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD}'
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    volumes:
      - ./.docker/redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    command: 'redis-server --save 120 1 --loglevel warning'
    networks:
      - nestjs-boilerplate-network

networks:
  nestjs-boilerplate-network:
    name: nestjs-boilerplate-network
    driver: bridge
