services:
  server:
    container_name: nestjs-boilerplate-dev
    image: nestjs-boilerplate-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
      - redis
      - mail
    command: >
      sh -c "pnpm start:dev"

  database:
    image: postgres:16
    container_name: nestjs-boilerplate-postgres
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
      TZ: 'UTC'
    ports:
      - '${DOCKER_DATABASE_PORT}:5432'
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-boilerplate-network

  mail:
    image: nestjs-boilerplate-mail:latest
    container_name: nestjs-boilerplate-mail
    build:
      context: .
      dockerfile: Dockerfile.maildev
    ports:
      - ${DOCKER_MAIL_PORT}:1025
      - ${DOCKER_MAIL_CLIENT_PORT}:1080
    networks:
      - nestjs-boilerplate-network
