services:
  server:
    container_name: nestjs-boilerplate
    image: nestjs-boilerplate:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_WORKER=false
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${APP_WEBSOCKET_PORT}:${APP_WEBSOCKET_PORT}'
    networks:
      - nestjs-boilerplate-network

  worker:
    container_name: nestjs-boilerplate-worker
    image: nestjs-boilerplate-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_WORKER=true
    ports:
      - '${APP_WORKER_PORT}:${APP_WORKER_PORT}'
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis:7.0.1-alpine
    container_name: nestjs-boilerplate-redis
    restart: always
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - ./.docker/redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    command: 'redis-server --save 120 1 --loglevel warning'
    networks:
      - nestjs-boilerplate-network

  # Solution to fix prometheus volume permission issue
  setup_prometheus:
    image: prom/prometheus:v3.0.1
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /prometheus
    volumes:
      - ./.docker/prometheus-data:/prometheus

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: nestjs-boilerplate-prometheus
    restart: unless-stopped
    ports:
      - ${DOCKER_PROMETHEUS_PORT}:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus.config.yml:/etc/prometheus/prometheus.yaml:ro
    depends_on:
      - setup_prometheus

networks:
  nestjs-boilerplate-network:
    name: nestjs-boilerplate-network
    driver: bridge
