services:
  server:
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${WEBSOCKET_PORT}:${WEBSOCKET_PORT}'
    networks:
      - nestjs-boilerplate-network

networks:
  nestjs-boilerplate-network:
    name: nestjs-boilerplate-network
    driver: bridge
