global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server'
    metrics_path: /${PROMETHEUS_METRICS_PATH}
    scrape_interval: 10s
    static_configs:
      - targets: ['server:${APP_PORT}']
